apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
subjects:
- kind: User
  name: admin-user@lab.local # AD User Name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin # must match the name of a Role or ClusterRole to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: development-CR
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["services", "endpoints", "pods", "secrets", "configmaps", "deployments", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: development-CRB
subjects:
- kind: Group
  name: hays-devs # AD Group Name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: development-CR # must match the name of the Role to bind to
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ntnx-system
  name: operations-role
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["services", "endpoints", "pods", "pods/log", "configmaps", "deployments", "jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntnx-system
  name: operations-RB
subjects:
- kind: Group
  name: hays-ops # AD Group Name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: operations-role # must match the name of the Role to bind to
  apiGroup: rbac.authorization.k8s.io

---

